controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    
# config/routes.yaml

# config/routes.yaml

main:
    path: /
    controller: App\Controller\MainController::index


login:
    path: /login
    controller: App\Controller\AuthController::login
    methods: ['POST']

register:
    path: /register
    controller: App\Controller\AuthController::register
    methods: ['POST']

logout:
    path: /logout
    controller: App\Controller\AuthController::logout
    methods: ['POST']

import_csv:
    path: /import/csv
    controller: App\Controller\CsvImporterController::index
    methods: [POST]


produit_create:
    path: /produits
    controller: App\Controller\ProduitController::create
    methods: [POST]

produit_update:
    path: /produits/{id}
    controller: App\Controller\ProduitController::update
    methods: [PUT]
    requirements:
        id: '\d+'

produit_get_all:
    path: /produits
    controller: App\Controller\ProduitController::getAll
    methods: [GET]

produit_get_by_id:
    path: /produits/{id}
    controller: App\Controller\ProduitController::getById
    methods: [GET]
    requirements:
        id: '\d+'

produit_get_by_code:
    path: /produits/code/{code}
    controller: App\Controller\ProduitController::getByCode
    methods: [GET]

produit_delete:
    path: /produits/{id}
    controller: App\Controller\ProduitController::delete
    methods: [DELETE]
    requirements:
        id: '\d+'

# config/routes/action_controller.yaml

ajouter_mes_produits:
    path: /ajouter-mesproduits/{produitId}
    controller: App\Controller\ActionController::ajouterAMesProduits
    methods: POST

supprimer_mes_produits:
    path: /supprimer-mesproduits/{produitId}
    controller: App\Controller\ActionController::supprimerDeMesProduits
    methods: DELETE

is_produit_dans_mes_produits:
    path: /is-produit-dans-mes-produits/{produitId}
    controller: App\Controller\ActionController::isProduitDansMesProduits
    methods: [GET]

aimer_produit:
    path: /like-produit/{produitId}
    controller: App\Controller\ActionController::aimerProduit
    methods: POST

ne_plus_aimer_produit:
    path: /unlike-produit/{produitId}
    controller: App\Controller\ActionController::nePlusAimerProduit
    methods: DELETE

get_mes_produits:
    path: /mes-produits
    controller: App\Controller\ActionController::getMesProduits
    methods: GET

get_produits_aimes:
    path: /liked
    controller: App\Controller\ActionController::getProduitsAimes
    methods: GET

is_produit_aime:
    path: /is-produit-aime/{produitId}
    controller: App\Controller\ActionController::isProduitAime
    methods: [GET]